# -*- coding: utf-8 -*-
"""67160368 - Week 04 - Assignemnt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtfXDsppW8xxVWSoB8nBmHUGZMaGLRKg
"""

from __future__ import annotations

from pathlib import Path
import re
import sqlite3
import pandas as pd

# Config
DATA_PATH = Path("retail_logs.csv")
DB_PATH = Path("retail_warehouse.db")    # ไฟล์ SQLite output

"""
ETL Pipeline สำหรับงาน Retail Store Logs
ลำดับ: Extract -> Transform -> Load -> Verify
Star Schema:
- 1 Fact Table: fact_sales
- 3 Dimension Tables: dim_location, dim_product, dim_date
"""


# Helper functions
def clean_text(value: object, default: str = "Unknown") -> str:
    if pd.isna(value) or str(value).strip() == "":
        return default
    return " ".join(str(value).strip().split()).title()


def clean_code(value: object, default: str = "Unknown") -> str:
    if pd.isna(value) or str(value).strip() == "":
        return default
    return " ".join(str(value).strip().split()).upper()


def clean_number(value: object) -> float | None:
    if pd.isna(value) or str(value).strip() == "":
        return None
    cleaned = re.sub(r"[^0-9.\-]", "", str(value))
    if cleaned in {"", ".", "-", "-."}:
        return None
    return float(cleaned)


def parse_mixed_date(value: object) -> pd.Timestamp:
    text = "" if pd.isna(value) else str(value).strip()
    for fmt in ["%Y-%m-%d", "%d-%b-%Y", "%d/%m/%Y"]:
        parsed = pd.to_datetime(text, format=fmt, errors="coerce")
        if not pd.isna(parsed):
            return parsed
    return pd.NaT


# EXTRACT
def extract() -> pd.DataFrame:
    df = pd.read_csv(DATA_PATH, dtype=str, encoding="utf-8-sig")
    df.columns = [c.strip().lower() for c in df.columns]
    print(f"[Extract] raw rows = {len(df):,}")
    print(f"[Extract] duplicate sale_id = {df.duplicated('sale_id').sum():,}")
    return df


# TRANSFORM
def transform(df: pd.DataFrame):
    # ลบรายการซ้ำ
    df = df.drop_duplicates(subset=["sale_id"], keep="first").copy()

    # Clean ข้อมูลตัวอักษร
    df["store_code"] = df["store_code"].apply(clean_code)
    df["branch"] = df["branch"].apply(clean_text)
    df["province"] = df["province"].apply(clean_text)
    df["region"] = df["region"].apply(clean_text)
    df["product_name"] = df["product_name"].apply(clean_text)
    df["category"] = df["category"].apply(clean_text)

    # Clean วันที่
    df["sale_date"] = df["sale_date"].apply(parse_mixed_date)

    # Clean ตัวเลข
    df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce").fillna(0).astype(int)
    df["unit_price"] = df["unit_price"].apply(clean_number)
    df["discount_percent"] = df["discount_percent"].apply(clean_number).fillna(0)

    # สร้างยอดขาย
    df["gross_sales"] = df["quantity"] * df["unit_price"]
    df["net_sales"] = (df["gross_sales"] * (1 - df["discount_percent"] / 100)).round(2)

    # ตัดข้อมูลที่ใช้ไม่ได้
    df = df.dropna(subset=["sale_date", "unit_price"])
    df = df[(df["quantity"] > 0) & (df["unit_price"] >= 0)].copy()

    # ---------- Dimension: Location ----------
    dim_location = (
        df[["store_code", "branch", "province", "region"]]
        .drop_duplicates()
        .sort_values(["store_code", "branch", "province", "region"])
        .reset_index(drop=True)
    )
    dim_location.insert(0, "location_id", range(1, len(dim_location) + 1))

    # ---------- Dimension: Product ----------
    dim_product = (
        df[["product_name", "category"]]
        .drop_duplicates()
        .sort_values(["category", "product_name"])
        .reset_index(drop=True)
    )
    dim_product.insert(0, "product_id", range(1, len(dim_product) + 1))

    # ---------- Dimension: Date ----------
    dim_date = (
        df[["sale_date"]]
        .drop_duplicates()
        .sort_values("sale_date")
        .reset_index(drop=True)
        .rename(columns={"sale_date": "full_date"})
    )
    dim_date["date_id"] = dim_date["full_date"].dt.strftime("%Y%m%d").astype(int)
    dim_date["day"] = dim_date["full_date"].dt.day
    dim_date["month"] = dim_date["full_date"].dt.month
    dim_date["month_name"] = dim_date["full_date"].dt.month_name()
    dim_date["quarter"] = "Q" + dim_date["full_date"].dt.quarter.astype(str)
    dim_date["year"] = dim_date["full_date"].dt.year
    dim_date = dim_date[["date_id", "full_date", "day", "month", "month_name", "quarter", "year"]]

    # ---------- Fact ----------
    mapped = df.merge(
        dim_location[["location_id", "store_code", "branch", "province", "region"]],
        on=["store_code", "branch", "province", "region"],
        how="left",
        validate="many_to_one",
    )
    mapped = mapped.merge(
        dim_product[["product_id", "product_name", "category"]],
        on=["product_name", "category"],
        how="left",
        validate="many_to_one",
    )
    mapped = mapped.merge(
        dim_date[["date_id", "full_date"]],
        left_on="sale_date",
        right_on="full_date",
        how="left",
        validate="many_to_one",
    )

    fact_sales = mapped[[
        "sale_id",
        "location_id",
        "product_id",
        "date_id",
        "quantity",
        "unit_price",
        "discount_percent",
        "gross_sales",
        "net_sales",
    ]].rename(columns={"sale_id": "transaction_id"})

    fact_sales[["location_id", "product_id", "date_id"]] = fact_sales[["location_id", "product_id", "date_id"]].astype(int)

    print(
        f"[Transform] location={len(dim_location)}, product={len(dim_product)}, date={len(dim_date)}, fact={len(fact_sales)}"
    )
    return dim_location, dim_product, dim_date, fact_sales


# LOAD
def load(dim_location, dim_product, dim_date, fact_sales):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("PRAGMA foreign_keys = ON;")
        conn.executescript("""
        DROP TABLE IF EXISTS fact_sales;
        DROP TABLE IF EXISTS dim_location;
        DROP TABLE IF EXISTS dim_product;
        DROP TABLE IF EXISTS dim_date;

        CREATE TABLE dim_location (
            location_id INTEGER PRIMARY KEY,
            store_code TEXT NOT NULL,
            branch TEXT NOT NULL,
            province TEXT NOT NULL,
            region TEXT NOT NULL
        );

        CREATE TABLE dim_product (
            product_id INTEGER PRIMARY KEY,
            product_name TEXT NOT NULL,
            category TEXT NOT NULL,
            UNIQUE(product_name, category)
        );

        CREATE TABLE dim_date (
            date_id INTEGER PRIMARY KEY,
            full_date TEXT NOT NULL UNIQUE,
            day INTEGER NOT NULL,
            month INTEGER NOT NULL,
            month_name TEXT NOT NULL,
            quarter TEXT NOT NULL,
            year INTEGER NOT NULL
        );

        CREATE TABLE fact_sales (
            transaction_id TEXT PRIMARY KEY,
            location_id INTEGER NOT NULL REFERENCES dim_location(location_id),
            product_id INTEGER NOT NULL REFERENCES dim_product(product_id),
            date_id INTEGER NOT NULL REFERENCES dim_date(date_id),
            quantity INTEGER NOT NULL CHECK(quantity > 0),
            unit_price REAL NOT NULL CHECK(unit_price >= 0),
            discount_percent REAL NOT NULL CHECK(discount_percent >= 0),
            gross_sales REAL NOT NULL CHECK(gross_sales >= 0),
            net_sales REAL NOT NULL CHECK(net_sales >= 0)
        );
        """)

        dim_location.to_sql("dim_location", conn, if_exists="append", index=False)
        dim_product.to_sql("dim_product", conn, if_exists="append", index=False)
        dim_date.to_sql("dim_date", conn, if_exists="append", index=False)
        fact_sales.to_sql("fact_sales", conn, if_exists="append", index=False)

        conn.commit()

    print(f"[Load] saved to {DB_PATH}")


# VERIFY
def verify():
    with sqlite3.connect(DB_PATH) as conn:
        sql = """
        SELECT
            l.branch,
            SUM(f.net_sales) AS total_sales
        FROM fact_sales f
        JOIN dim_location l ON f.location_id = l.location_id
        GROUP BY l.branch
        ORDER BY total_sales DESC
        LIMIT 5;
        """
        result = pd.read_sql_query(sql, conn)

    print("[Verify] Top 5 branches by net sales")
    print(result.to_string(index=False))


if __name__ == "__main__":
    raw = extract()
    dim_location, dim_product, dim_date, fact_sales = transform(raw)
    load(dim_location, dim_product, dim_date, fact_sales)
    verify()
    print("ETL Pipeline run successfully!")